@FieldsAreNotNullByDefault
@MethodsReturnNotNullByDefault
@ParametersAreNullableByDefault
package net.thenextlvl.service.wrapper;

import core.annotation.FieldsAreNotNullByDefault;
import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNullableByDefault;