@FieldsAreNotNullByDefault
@MethodsReturnNullableByDefault
@ParametersAreNullableByDefault
package net.thenextlvl.services.hook.permission;

import core.annotation.FieldsAreNotNullByDefault;
import core.annotation.MethodsReturnNullableByDefault;
import core.annotation.ParametersAreNullableByDefault;